---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: whoami-

labels:
  - pairs:
      app: whoami
    includeSelectors: true

resources:
  - ./deployment.yaml
  - ./ingress.yaml
  - ./service.yaml
