---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  grafana.ini: |
    [auth.basic]
    enabled = false

    [security]
    allow_embedding = true

    [database]
    type = postgres
    url = $__env{POSTGRES_URL}

    [remote_cache]
    type = redis
    connstr = addr=grafana-redis-service
