---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: docker.io/grafana/grafana:8.0.3
          env:
            - name: GF_INSTALL_PLUGINS
              value: flant-statusmap-panel,ae3e-plotly-panel
            - name: GF_SERVER_ROOT_URL
              value: https://grafana.durbin.casa
            - name: GF_RENDERING_SERVER_URL
              value: http://grafana_renderer:8081/render
            - name: GF_RENDERING_CALLBACK_URL
              value: http://grafana:3000
            - name: GF_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gf-database-url
                  key: password
          ports:
            - name: web
              containerPort: 3000
