---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./grafana_config.yaml
  - ./grafana_deployment.yaml
  - ./grafana_service.yaml
  - ./ingress.yaml
  - ./postgres_deployment.yaml
  - ./postgres_service.yaml
  - ./redis_deployment.yaml
  - ./redis_service.yaml
  - ./postgres_volume.yaml

secretGenerator:
  - name: grafana-secrets
    envs:
      - grafana.env
