---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: grafana-

labels:
  - pairs:
      app: grafana
    includeSelectors: true

resources:
  - ./grafana_config.yaml
  - ./grafana_deployment.yaml
  - ./grafana_service.yaml
  - ./ingress.yaml
  - ./redis_deployment.yaml
  - ./redis_service.yaml
  - ../postgres

secretGenerator:
  - name: grafana-secrets
    envs:
      - grafana.env
