---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./grafana_config.yaml
  - ./grafana_deployment.yaml
  - ./grafana_service.yaml
  - ./ingress.yaml
  - ./postgres_deployment.yaml
  - ./postgres_service.yaml
