---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: grafana-

labels:
  - pairs:
      app: grafana
    includeSelectors: true

resources:
  - ./config.yaml
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
  - ../redis
  - ../postgres

secretGenerator:
  - name: grafana-secrets
    envs:
      - grafana.env

replacements:
  - source:
      kind: Secret
      name: grafana-secrets
    targets:
      - select:
          name: grafana-postgres-deployment
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=postgres].env.[name=POSTGRES_PASSWORD].valueFrom.secretKeyRef.name
