---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: adminer-

labels:
  - pairs:
      app: adminer
    includeSelectors: true

resources:
  - ./deployment.yaml
  - ./ingress.yaml
  - ./service.yaml
