---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    component: postgres
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:13
          # env:
          #   - name: POSTGRES_USER
          #     value: grafana
          #   - name: POSTGRES_DB
          #     value: grafana
          #   - name: POSTGRES_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: grafana-secrets
          #         key: POSTGRES_PASSWORD
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgres
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
