---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: postgres-

labels:
  - pairs:
      app: postgres
    includeSelectors: true

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./volume.yaml
