---
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'
      - 'beat'

homeassistant:
  name: home
  latitude: 0
  longitude: 0
  elevation: 0
  unit_system: imperial
  time_zone: America/Denver

recorder:
  db_url: !env_var POSTGRES_URL
