---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: redis-

labels:
  - pairs:
      app: redis
    includeSelectors: true

resources:
  - ./deployment.yaml
  - ./service.yaml
