---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: homeassistant-

labels:
  - pairs:
      app: homeassistant
    includeSelectors: true

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./ingress.yaml
  - ./postgres_volume.yaml
  - ../postgres

configMapGenerator:
  - name: config
    files:
      - ./configuration/configuration.yaml

secretGenerator:
  - name: secrets
    envs:
      - homeassistant.env

replacements:
  - source:
      kind: Secret
      name: secrets
    targets:
      - select:
          name: homeassistant-postgres-deployment
          kind: Deployment
        fieldPaths:
          - spec.template.spec.containers.[name=postgres].env.[name=POSTGRES_PASSWORD].valueFrom.secretKeyRef.name
          - spec.template.spec.containers.[name=postgres].env.[name=POSTGRES_USER].valueFrom.secretKeyRef.name
          - spec.template.spec.containers.[name=postgres].env.[name=POSTGRES_DB].valueFrom.secretKeyRef.name
