---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/tmp/homeassistant_postgres'
